Database:
  cockroach:
    Host: localhost
    Port: 26257
    Database: zitadel
    Options: ""
    User:
      Username: zitadel
    Admin:
      Username: root

Caches:
  Connectors:
    Memory:
      Enabled: true
      AutoPrune:
        Interval: 30s
        TimeOut: 1s 
  Instance:
    Connector: "memory"
    MaxAge: 1h
    LastUsage: 30m
    Log:
      Level: info
      AddSource: true
      Formatter:
        Format: text
